"""changes in constraints access token

Revision ID: 0fbff4474d66
Revises: aa39f3d94c6f
Create Date: 2025-05-03 17:02:33.645649

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "0fbff4474d66"
down_revision: Union[str, None] = "aa39f3d94c6f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("accesstoken_user_id_key", "accesstoken", type_="unique")
    op.drop_constraint("accesstoken_user_id_fkey", "accesstoken", type_="foreignkey")
    op.create_foreign_key(None, "accesstoken", "user", ["user_id"], ["id"], ondelete="cascade")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "accesstoken", type_="foreignkey")
    op.create_foreign_key("accesstoken_user_id_fkey", "accesstoken", "user", ["user_id"], ["id"])
    op.create_unique_constraint("accesstoken_user_id_key", "accesstoken", ["user_id"])
    # ### end Alembic commands ###
