"""change types int -> uuid, float -> decimal

Revision ID: 1258b243fa83
Revises: f349405f802e
Create Date: 2025-05-02 15:00:53.188225

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1258b243fa83"
down_revision: Union[str, None] = "f349405f802e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "level",
        "level_number",
        existing_type=sa.INTEGER(),
        type_=sa.Numeric(),
        existing_comment="Номер уровня (например: 5)",
        existing_nullable=False,
    )
    op.alter_column(
        "level",
        "required_xp",
        existing_type=sa.INTEGER(),
        type_=sa.Numeric(),
        existing_comment="Необходимый опыт для достижения уровня",
        existing_nullable=False,
    )
    op.alter_column(
        "physical_business_settings",
        "size_sq_meters",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(),
        existing_comment="Площадь помещения в квадратных метрах",
        existing_nullable=False,
    )
    op.alter_column(
        "profit_physical_business",
        "amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(),
        existing_comment="Сумма прибыли",
        existing_nullable=False,
    )
    op.alter_column(
        "profit_virtual_business",
        "amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(),
        existing_comment="Сумма прибыли в виртуальной валюте",
        existing_nullable=False,
    )
    op.alter_column(
        "stock",
        "current_price",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(),
        existing_comment="Текущая цена акции",
        existing_nullable=False,
    )
    op.alter_column(
        "transaction",
        "amount",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(),
        existing_comment="Сумма транзакции",
        existing_nullable=False,
    )
    op.alter_column(
        "user_briefcase",
        "balance",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(),
        existing_comment="Текущий баланс виртуальных средств",
        existing_nullable=False,
    )
    op.alter_column(
        "user_stats",
        "total_businesses",
        existing_type=sa.INTEGER(),
        type_=sa.Numeric(),
        existing_comment="Общее количество бизнесов пользователя",
        existing_nullable=False,
    )
    op.alter_column(
        "user_stats",
        "total_capital",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(),
        existing_comment="Совокупный капитал во всех бизнесах",
        existing_nullable=False,
    )
    op.alter_column(
        "user_stats",
        "success_rate",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(),
        existing_comment="Рейтинг успешности от 0.0 до 1.0",
        existing_nullable=False,
    )
    op.alter_column(
        "virtual_business_settings",
        "initial_capital",
        existing_type=sa.DOUBLE_PRECISION(precision=53),
        type_=sa.Numeric(),
        existing_comment="Начальный капитал в виртуальной валюте",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "virtual_business_settings",
        "initial_capital",
        existing_type=sa.Numeric(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_comment="Начальный капитал в виртуальной валюте",
        existing_nullable=False,
    )
    op.alter_column(
        "user_stats",
        "success_rate",
        existing_type=sa.Numeric(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_comment="Рейтинг успешности от 0.0 до 1.0",
        existing_nullable=False,
    )
    op.alter_column(
        "user_stats",
        "total_capital",
        existing_type=sa.Numeric(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_comment="Совокупный капитал во всех бизнесах",
        existing_nullable=False,
    )
    op.alter_column(
        "user_stats",
        "total_businesses",
        existing_type=sa.Numeric(),
        type_=sa.INTEGER(),
        existing_comment="Общее количество бизнесов пользователя",
        existing_nullable=False,
    )
    op.alter_column(
        "user_briefcase",
        "balance",
        existing_type=sa.Numeric(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_comment="Текущий баланс виртуальных средств",
        existing_nullable=False,
    )
    op.alter_column(
        "transaction",
        "amount",
        existing_type=sa.Numeric(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_comment="Сумма транзакции",
        existing_nullable=False,
    )
    op.alter_column(
        "stock",
        "current_price",
        existing_type=sa.Numeric(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_comment="Текущая цена акции",
        existing_nullable=False,
    )
    op.alter_column(
        "profit_virtual_business",
        "amount",
        existing_type=sa.Numeric(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_comment="Сумма прибыли в виртуальной валюте",
        existing_nullable=False,
    )
    op.alter_column(
        "profit_physical_business",
        "amount",
        existing_type=sa.Numeric(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_comment="Сумма прибыли",
        existing_nullable=False,
    )
    op.alter_column(
        "physical_business_settings",
        "size_sq_meters",
        existing_type=sa.Numeric(),
        type_=sa.DOUBLE_PRECISION(precision=53),
        existing_comment="Площадь помещения в квадратных метрах",
        existing_nullable=False,
    )
    op.alter_column(
        "level",
        "required_xp",
        existing_type=sa.Numeric(),
        type_=sa.INTEGER(),
        existing_comment="Необходимый опыт для достижения уровня",
        existing_nullable=False,
    )
    op.alter_column(
        "level",
        "level_number",
        existing_type=sa.Numeric(),
        type_=sa.INTEGER(),
        existing_comment="Номер уровня (например: 5)",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
