"""change constraint in course

Revision ID: 2f42fbace491
Revises: bf0c4de68d4f
Create Date: 2025-05-02 23:22:58.487846

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2f42fbace491"
down_revision: Union[str, None] = "bf0c4de68d4f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("course", "category_id", existing_type=sa.UUID(), nullable=True, existing_comment="Категория курса")
    op.drop_constraint("course_category_id_fkey", "course", type_="foreignkey")
    op.create_foreign_key(None, "course", "course_category", ["category_id"], ["id"], ondelete="SET NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "course", type_="foreignkey")
    op.create_foreign_key("course_category_id_fkey", "course", "course_category", ["category_id"], ["id"])
    op.alter_column(
        "course", "category_id", existing_type=sa.UUID(), nullable=False, existing_comment="Категория курса"
    )
    # ### end Alembic commands ###
