"""add timestamp mixin for business setting (virtual plus physical)

Revision ID: 9ff6f8a9bcbb
Revises: d5ad1b29fbef
Create Date: 2025-05-08 16:21:08.922991

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9ff6f8a9bcbb"
down_revision: Union[str, None] = "d5ad1b29fbef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("physical_business_settings", sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.add_column("physical_business_settings", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    op.add_column("virtual_business_settings", sa.Column("created_at", sa.DateTime(timezone=True), nullable=False))
    op.add_column("virtual_business_settings", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("virtual_business_settings", "updated_at")
    op.drop_column("virtual_business_settings", "created_at")
    op.drop_column("physical_business_settings", "updated_at")
    op.drop_column("physical_business_settings", "created_at")
    # ### end Alembic commands ###
