"""add image mixin

Revision ID: bf0c4de68d4f
Revises: c5ff0fe038d9
Create Date: 2025-05-02 20:42:15.136256

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bf0c4de68d4f"
down_revision: Union[str, None] = "c5ff0fe038d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("course", sa.Column("image_url", sa.String(length=255), nullable=True, comment="URL изображения"))
    op.add_column("lesson", sa.Column("image_url", sa.String(length=255), nullable=True, comment="URL изображения"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("lesson", "image_url")
    op.drop_column("course", "image_url")
    # ### end Alembic commands ###
