"""change business fields -- physical + virtual

Revision ID: d5ad1b29fbef
Revises: f10c3f3ca030
Create Date: 2025-05-07 21:10:03.228076

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d5ad1b29fbef"
down_revision: Union[str, None] = "f10c3f3ca030"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "business",
        sa.Column(
            "initial_investment",
            sa.Numeric(precision=12, scale=2),
            nullable=False,
            comment="Первоначальные инвестиции в рублях/валюте",
        ),
    )
    op.add_column(
        "business",
        sa.Column(
            "operational_costs",
            sa.Numeric(precision=12, scale=2),
            nullable=False,
            comment="Базовые операционные расходы в месяц",
        ),
    )
    op.add_column(
        "business",
        sa.Column(
            "expected_revenue", sa.Numeric(precision=12, scale=2), nullable=False, comment="Ожидаемый месячный доход"
        ),
    )
    op.add_column(
        "business",
        sa.Column("break_even_months", sa.Numeric(), nullable=True, comment="Расчетный срок окупаемости в месяцах"),
    )
    op.add_column(
        "physical_business_settings",
        sa.Column(
            "average_salary",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            comment="Средняя зарплата сотрудника в месяц",
        ),
    )
    op.add_column(
        "physical_business_settings",
        sa.Column("rent_cost", sa.Numeric(precision=10, scale=2), nullable=False, comment="Стоимость аренды в месяц"),
    )
    op.add_column(
        "physical_business_settings",
        sa.Column(
            "equipment_maintenance_cost",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            comment="Расходы на обслуживание оборудования в месяц",
        ),
    )
    op.add_column(
        "physical_business_settings",
        sa.Column(
            "tax_rate", sa.Numeric(precision=5, scale=3), nullable=False, comment="Налоговая ставка (0.15 для 15%)"
        ),
    )
    op.add_column(
        "physical_business_settings",
        sa.Column(
            "utilities_cost", sa.Numeric(precision=10, scale=2), nullable=False, comment="Коммунальные расходы в месяц"
        ),
    )
    op.add_column(
        "physical_business_settings",
        sa.Column(
            "marketing_budget", sa.Numeric(precision=10, scale=2), nullable=False, comment="Бюджет на маркетинг в месяц"
        ),
    )
    op.alter_column(
        "physical_business_settings",
        "location",
        existing_type=sa.VARCHAR(length=255),
        comment="Координаты или адрес местоположения",
        existing_comment="Координаты местоположения (например: '55.7558,37.6173')",
        existing_nullable=False,
    )
    op.alter_column(
        "physical_business_settings",
        "size_sq_meters",
        existing_type=sa.NUMERIC(),
        comment="Площадь помещения (м²)",
        existing_comment="Площадь помещения в квадратных метрах",
        existing_nullable=False,
    )
    op.alter_column(
        "physical_business_settings",
        "equipment",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        comment="Оборудование: {'тип': количество}",
        existing_comment="Оборудование в формате JSON (например: {'станки': 5, 'транспорт': 2})",
        existing_nullable=False,
    )
    op.add_column(
        "virtual_business_settings",
        sa.Column(
            "electricity_cost",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            comment="Стоимость электроэнергии в месяц",
        ),
    )
    op.add_column(
        "virtual_business_settings",
        sa.Column(
            "hardware_cost",
            sa.Numeric(precision=12, scale=2),
            nullable=False,
            comment="Стоимость оборудования (амортизация в месяц)",
        ),
    )
    op.add_column(
        "virtual_business_settings",
        sa.Column("hashrate", sa.Integer(), nullable=False, comment="Хэшрейт оборудования (TH/s)"),
    )
    op.add_column(
        "virtual_business_settings",
        sa.Column("mining_difficulty", sa.Integer(), nullable=False, comment="Текущая сложность майнинга"),
    )
    op.add_column(
        "virtual_business_settings",
        sa.Column("pool_fees", sa.Numeric(precision=5, scale=3), nullable=False, comment="Комиссия пула (0.02 для 2%)"),
    )
    op.add_column(
        "virtual_business_settings",
        sa.Column(
            "crypto_price", sa.Numeric(precision=12, scale=2), nullable=False, comment="Текущая цена криптовалюты"
        ),
    )
    op.add_column(
        "virtual_business_settings",
        sa.Column(
            "risk_multiplier", sa.Numeric(precision=3, scale=2), nullable=False, comment="Множитель риска для расчетов"
        ),
    )
    op.alter_column(
        "virtual_business_settings",
        "initial_capital",
        existing_type=sa.NUMERIC(),
        comment=None,
        existing_comment="Начальный капитал в виртуальной валюте",
        existing_nullable=False,
    )
    op.alter_column(
        "virtual_business_settings",
        "risk_level",
        existing_type=sa.INTEGER(),
        comment=None,
        existing_comment="Уровень риска от 1 (низкий) до 5 (высокий)",
        existing_nullable=False,
    )
    op.alter_column(
        "virtual_business_settings",
        "portfolio",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        comment="Структура портфеля",
        existing_comment="Структура портфеля (например: {'BTC': 60, 'ETH': 40})",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "virtual_business_settings",
        "portfolio",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        comment="Структура портфеля (например: {'BTC': 60, 'ETH': 40})",
        existing_comment="Структура портфеля",
        existing_nullable=False,
    )
    op.alter_column(
        "virtual_business_settings",
        "risk_level",
        existing_type=sa.INTEGER(),
        comment="Уровень риска от 1 (низкий) до 5 (высокий)",
        existing_nullable=False,
    )
    op.alter_column(
        "virtual_business_settings",
        "initial_capital",
        existing_type=sa.NUMERIC(),
        comment="Начальный капитал в виртуальной валюте",
        existing_nullable=False,
    )
    op.drop_column("virtual_business_settings", "risk_multiplier")
    op.drop_column("virtual_business_settings", "crypto_price")
    op.drop_column("virtual_business_settings", "pool_fees")
    op.drop_column("virtual_business_settings", "mining_difficulty")
    op.drop_column("virtual_business_settings", "hashrate")
    op.drop_column("virtual_business_settings", "hardware_cost")
    op.drop_column("virtual_business_settings", "electricity_cost")
    op.alter_column(
        "physical_business_settings",
        "equipment",
        existing_type=postgresql.JSON(astext_type=sa.Text()),
        comment="Оборудование в формате JSON (например: {'станки': 5, 'транспорт': 2})",
        existing_comment="Оборудование: {'тип': количество}",
        existing_nullable=False,
    )
    op.alter_column(
        "physical_business_settings",
        "size_sq_meters",
        existing_type=sa.NUMERIC(),
        comment="Площадь помещения в квадратных метрах",
        existing_comment="Площадь помещения (м²)",
        existing_nullable=False,
    )
    op.alter_column(
        "physical_business_settings",
        "location",
        existing_type=sa.VARCHAR(length=255),
        comment="Координаты местоположения (например: '55.7558,37.6173')",
        existing_comment="Координаты или адрес местоположения",
        existing_nullable=False,
    )
    op.drop_column("physical_business_settings", "marketing_budget")
    op.drop_column("physical_business_settings", "utilities_cost")
    op.drop_column("physical_business_settings", "tax_rate")
    op.drop_column("physical_business_settings", "equipment_maintenance_cost")
    op.drop_column("physical_business_settings", "rent_cost")
    op.drop_column("physical_business_settings", "average_salary")
    op.drop_column("business", "break_even_months")
    op.drop_column("business", "expected_revenue")
    op.drop_column("business", "operational_costs")
    op.drop_column("business", "initial_investment")
    # ### end Alembic commands ###
