"""add lesson url to course

Revision ID: f10c3f3ca030
Revises: 0fbff4474d66
Create Date: 2025-05-06 21:27:57.396269

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f10c3f3ca030"
down_revision: Union[str, None] = "0fbff4474d66"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "course", sa.Column("lesson_url", sa.String(length=255), nullable=True, comment="Ссылка на видео по курсу")
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("course", "lesson_url")
    # ### end Alembic commands ###
